from __future__ import annotations
import json
from collections import defaultdict
from datetime import datetime, timezone


def generate_navigator_layer(sessions, title: str = "ps_classifier analysis") -> str:
    """Generate an ATT&CK Navigator 4.x JSON layer from detected techniques."""
    tech_data: dict[str, dict] = defaultdict(
        lambda: {"max_sev": 0, "session_count": 0, "rules": set()}
    )

    for s in sessions:
        seen: set[str] = set()
        for block in s.blocks:
            for finding in block.findings:
                mid = finding.mitre_id
                if not mid:
                    continue
                td = tech_data[mid]
                td["max_sev"] = max(td["max_sev"], finding.severity)
                td["rules"].add(finding.technique_id)
                seen.add(mid)
        for mid in seen:
            tech_data[mid]["session_count"] += 1

    techniques = [
        {
            "techniqueID": mid,
            "score": td["max_sev"],
            "color": "",
            "comment": (
                f"Detected in {td['session_count']} session(s). "
                f"Rules: {', '.join(sorted(td['rules']))}"
            ),
            "enabled": True,
            "metadata": [],
            "links": [],
            "showSubtechniques": True,
        }
        for mid, td in tech_data.items()
    ]
    techniques.sort(key=lambda t: -t["score"])

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    layer = {
        "name": title,
        "versions": {"attack": "14", "navigator": "4.9", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": f"Generated by ps_classifier — {ts}",
        "filters": {"platforms": ["Windows"]},
        "sorting": 3,
        "layout": {
            "layout": "side",
            "aggregateFunction": "max",
            "showID": True,
            "showName": True,
            "showAggregateScores": True,
            "countUnscored": False,
            "expandedSubtechniques": "annotated",
        },
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": ["#fce8e8", "#d32f2f"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "Low (≤25)",       "color": "#fce8e8"},
            {"label": "Medium (≤50)",    "color": "#ef9a9a"},
            {"label": "High (≤75)",      "color": "#e53935"},
            {"label": "Critical (≤100)", "color": "#d32f2f"},
        ],
        "metadata": [],
        "links": [],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#f5f5f5",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }

    return json.dumps(layer, indent=2)
